//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class days_of_jobs
    {
        public int id { get; set; }
        public Nullable<int> id_job { get; set; }
        public Nullable<int> id_day { get; set; }
        public Nullable<int> num_priority { get; set; }
    
        public virtual days_ days_ { get; set; }
        public virtual job job { get; set; }
    }
}
