//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WORKERSEntities : DbContext
    {
        public WORKERSEntities()
            : base("name=WORKERSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<area> areas { get; set; }
        public virtual DbSet<candidate> candidates { get; set; }
        public virtual DbSet<city> cities { get; set; }
        public virtual DbSet<days_> days_ { get; set; }
        public virtual DbSet<days_of_candidates> days_of_candidates { get; set; }
        public virtual DbSet<days_of_jobs> days_of_jobs { get; set; }
        public virtual DbSet<favorite_req> favorite_req { get; set; }
        public virtual DbSet<gender> genders { get; set; }
        public virtual DbSet<job> jobs { get; set; }
        public virtual DbSet<requiers_to_jobs> requiers_to_jobs { get; set; }
        public virtual DbSet<requirement> requirements { get; set; }
        public virtual DbSet<scheduling> schedulings { get; set; }
        public virtual DbSet<score_of_jobs> score_of_jobs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<company> companies { get; set; }
    }
}
