//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class requiers_to_jobs
    {
        public int id_req_to_job { get; set; }
        public Nullable<int> id_job { get; set; }
        public Nullable<int> id_requirment { get; set; }
        public Nullable<double> score { get; set; }
    
        public virtual job job { get; set; }
        public virtual requirement requirement { get; set; }
    }
}
