//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class scheduling
    {
        public int id_schedule { get; set; }
        public Nullable<int> id_candidate { get; set; }
        public Nullable<int> id_job { get; set; }
    
        public virtual candidate candidate { get; set; }
        public virtual job job { get; set; }
    }
}
